name: Rhitta
version: 2.0.0
main: me.reno.rhitta.RhittaPlugin
api-version: '26.1'

commands:
  rhitta:
    description: Rhitta abilities and controls
    usage: /rhitta <help|ability|status|remove>
    aliases:
      - r